Repository tazama-lf/lumberjack, pull requests merged in 2024-10, with the labels that each got.

#151 feat: env/validation
  .npmrc
  Dockerfile
  package-lock.json
  package.json
  src/config/server.ts
  src/index.ts
  src/services/logger.ts
Labels: enhancement

#157 fix: Issue 227 Add Tazama into to LICENSE
  LICENSE
Labels: bug

#163 refactor: use upstream config
  .env.example
  Dockerfile
  package-lock.json
  package.json
  src/config/server.ts
  src/services/logger.ts
Labels: refactor
